### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by Luni-4**

### CODE REVIEW

**Comment by Luni-4** [comment]
> Possibly I should bite the bullet and go over all those crates and make sure the feature to build a local copy is present and working...

That would be a good approach for me, so it is not necessary to install all these dependencies.

**Comment by lu-zero** [comment]
I guess we could open issues about it for the hacktoberfest :)

**Comment by Luni-4** [comment]
> I guess we could open issues about it for the hacktoberfest :)

Yep, I agree :+1:

**Comment by Luni-4** [comment]
@lu-zero I was thinking about this PR, perhaps we should merge it, at least we can verify if `ave` builds or not. We could always change the deps chain later. What do you think about this plan?

**Comment by lu-zero** [comment]
Sure, we can iterate over it once we have the build features in

**Comment by Luni-4** [comment]
> Sure, we can iterate over it once we have the build features in

Yep, I agree.

**Pull request merged**
